### PR TITLE
add BCS deserialization. (#33)

### PR DESCRIPTION
**Pull request by 0xpause**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #33 

## What is the new behavior?

- Support BCS deserialization for: bool, u64, u128, vector\<bool\>, vector\<u8\>, vector\<u64\>, vector\<u128\>.

### CODE REVIEW

**Comment by 0xpause** [comment]
`mpm package prove` 验证失败，我没有写 spec 函数，也不明白为什么会 abort 。 可以给些建议吗？

**Comment by jolestar** [comment]
There are some implementations of BCS deserializer, Please help migrate some functions or test cases from the repo.

https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/src/modules/bcs/BCSDeserializer.move

https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/unittest/bcs/BCSDeserializerTest.move

**Comment by 0xpause** [comment]
> There are some implementations of BCS deserializer, Please help migrate some functions or test cases from the repo.
> 
> https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/src/modules/bcs/BCSDeserializer.move
> 
> https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/unittest/bcs/BCSDeserializerTest.move

This implementation is completed and covers almost all cases. If it's OK to use this implementation directly?

**Comment by jolestar** [comment]
> > There are some implementations of BCS deserializer, Please help migrate some functions or test cases from the repo.
> > https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/src/modules/bcs/BCSDeserializer.move
> > https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/unittest/bcs/BCSDeserializerTest.move
> 
> This implementation is completed and covers almost all cases. If it's OK to use this implementation directly?

Should we use `BCS.move` or use another module such as `BCSDeserializer.move`?

@wubuku What is your opinion?

**Comment by wubuku** [comment]
> > > There are some implementations of BCS deserializer, Please help migrate some functions or test cases from the repo.
> > > https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/src/modules/bcs/BCSDeserializer.move
> > > https://github.com/wubuku/StarcoinNSDemo/blob/main/move-contracts/unittest/bcs/BCSDeserializerTest.move
> > 
> > 
> > This implementation is completed and covers almost all cases. If it's OK to use this implementation directly?
> 
> Should we use `BCS.move` or use another module such as `BCSDeserializer.move`?
> 
> @wubuku What is your opinion?

I think in BCS module directly is Ok.

**Comment by wubuku** [comment]
I think an important issue is the need to let the primitive deserialization function return `new_offset`, which helps the combination to deserialize complex structures.

You guys are completely free to migrate that code to Starcoin Framework, and have no problem with that.

**Pull request closed without merging**
